// Viewport BiomeType — these are the authoritative biome values used by Three.js terrain
export type ViewportBiomeType = 'pine' | 'cyber' | 'canyon' | 'alien' | 'ruins';

// Maps viewport biome → sceneGraph.schema biome value
export const BIOME_TO_SCHEMA: Record<ViewportBiomeType, 'forest' | 'urban' | 'desert' | 'custom' | 'dungeon'> = {
  pine: 'forest',
  cyber: 'urban',
  canyon: 'desert',
  alien: 'custom',
  ruins: 'dungeon',
};

export type AgentId =
  | 'parent'
  | 'story'
  | 'character'
  | 'world'
  | 'npc'
  | 'quest'
  | 'dialogue';

export type GenerationMode = 'detailed' | 'quick';

export interface WorldRequest {
  sessionId: string;
  rawPrompt: string;
  mode: GenerationMode;
  imageDescriptions?: Array<{ tag: 'character' | 'scene' | 'texture' | 'map'; description: string }>;
  document?: string;
}

export interface SelectionContext {
  center: { x: number; z: number };
  radiusWorldUnits: number;
  regions: string[];
  npcs: string[];
  landmarks: string[];
  activeQuests: string[];
  biome: ViewportBiomeType;
}

export interface AgentSummary {
  agentId: AgentId;
  sessionId: string;
  summary: string;        // short human-readable summary, generated by code not LLM
  nodeCount: number;
  edgeCount: number;
  durationMs: number;
}

export interface ConflictEntry {
  agentId: AgentId;
  type: 'missing_ref' | 'duplicate_name' | 'invalid_faction' | 'invalid_region' | 'dialogue_too_long' | 'schema_mismatch';
  description: string;
  retryCount: number;
}

export interface OrchestratorProgressEvent {
  sessionId: string;
  agentId: AgentId | 'compile' | 'review';
  status: 'started' | 'completed' | 'retrying' | 'failed';
  message: string;
  percentComplete: number;
  conflicts?: ConflictEntry[];
}

export interface RegionElevation {
  regionId: string;
  centerX: number;
  centerZ: number;
  radius: number;
  amplitude: number; // 0–20, fed to getElevation per-region
}
